# This is the network config written by 'subiquity'
network:
  ethernets:
    enp1s0:
      dhcp4: false
      nameservers:
        addresses:
          [8.8.8.8, 114.114.114.114]
      addresses:
        - 192.168.137.254/24
        - 192.168.8.254/24
        - 192.168.3.254/24
      routes:
        - to: 0.0.0.0/0
          via: 192.168.137.1
          metric: 200
        - to: 0.0.0.0/0
          via: 192.168.8.1
          metric: 300
        - to: 0.0.0.0/0
          via: 192.168.3.1
          metric: 400
  version: 2
